name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Go to the frontend folder
        run: cd frontend && ls
      - name: Login DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker frontend image
        run: ls && docker build -t youssefelmajdoul/rentcaremirats-frontend:latest .

      - name: Push the frontend to DockerHub
        run: docker push youssefelmajdoul/rentcaremirats-frontend:latest

      - name: Go to the backend folder
        run: cd ../backend

      - name: Build the Docker frontend image
        run: docker build -t youssefelmajdoul/rentcaremirats-backend:latest .

      - name: Push the frontend to DockerHub
        run: docker push youssefelmajdoul/rentcaremirats-backend:latest
