name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Go to the frontend folder
        run: cd frontend
      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u youssefelmajdoul -p $DOCKER_PASSWORD

      - name: Build the Docker frontend image
        run: docker build -t rentcaremirats

      - name: Push the frontend to DockerHub
        run: docker push youssefelmajdoul/rentcaremirats-frontend:latest

      - name: Go to the backend folder
        run: cd ../backend

      - name: Build the Docker frontend image
        run: docker build -t rentcaremirats

      - name: Push the frontend to DockerHub
        run: docker push youssefelmajdoul/rentcaremirats-backend:latest
